services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    depends_on:
      - web

  database:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

